import { createElement } from 'lwc';
import Metronome from 'c/metronome';

describe('c-metronome', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-metronome', {
            is: Metronome
        });

        


        document.body.appendChild(element);

        expect(element.bpm).toEqual(100);



    });
});