export const pianoNotes = [
    {"instrument" : "piano", "key" : "C0", "color" : "white", "name" : "C", "octave" : "0"},
    {"instrument" : "piano", "key" : "C#0", "color" : "black", "name" : "C", "octave" : "0"},
    {"instrument" : "piano", "key" : "D0", "color" : "white", "name" : "D", "octave" : "0"},
    {"instrument" : "piano", "key" : "D#0", "color" : "black", "name" : "D", "octave" : "0"},
    {"instrument" : "piano", "key" : "E0", "color" : "white", "name" : "E", "octave" : "0"},
    {"instrument" : "piano", "key" : "F0", "color" : "white", "name" : "F", "octave" : "0"},
    {"instrument" : "piano", "key" : "F#0", "color" : "black", "name" : "F", "octave" : "0"},
    {"instrument" : "piano", "key" : "G0", "color" : "white", "name" : "G", "octave" : "0"},
    {"instrument" : "piano", "key" : "G#0", "color" : "black", "name" : "G", "octave" : "0"},
    {"instrument" : "piano", "key" : "A0", "color" : "white", "name" : "A", "octave" : "0"},
    {"instrument" : "piano", "key" : "A#0", "color" : "black", "name" : "A", "octave" : "0"},
    {"instrument" : "piano", "key" : "B0", "color" : "white", "name" : "B", "octave" : "1"},
    {"instrument" : "piano", "key" : "C1", "color" : "white", "name" : "C", "octave" : "1"},
    {"instrument" : "piano", "key" : "C#1", "color" : "black", "name" : "C", "octave" : "1"},
    {"instrument" : "piano", "key" : "D1", "color" : "white", "name" : "D", "octave" : "1"},
    {"instrument" : "piano", "key" : "D#1", "color" : "black", "name" : "D", "octave" : "1"},
    {"instrument" : "piano", "key" : "E1", "color" : "white", "name" : "E", "octave" : "1"},
    {"instrument" : "piano", "key" : "F1", "color" : "white", "name" : "F", "octave" : "1"},
    {"instrument" : "piano", "key" : "F#1", "color" : "black", "name" : "F", "octave" : "1"},
    {"instrument" : "piano", "key" : "G1", "color" : "white", "name" : "G", "octave" : "1"},
    {"instrument" : "piano", "key" : "G#1", "color" : "black", "name" : "G", "octave" : "1"},
    {"instrument" : "piano", "key" : "A1", "color" : "white", "name" : "A", "octave" : "1"},
    {"instrument" : "piano", "key" : "A#1", "color" : "black", "name" : "A", "octave" : "1"},
    {"instrument" : "piano", "key" : "B1", "color" : "white", "name" : "B", "octave" : "1"}, 
    {"instrument" : "piano", "key" : "C2", "color" : "white", "name" : "C", "octave" : "2"},
    {"instrument" : "piano", "key" : "C#2", "color" : "black", "name" : "C", "octave" : "2"},
    {"instrument" : "piano", "key" : "D2", "color" : "white", "name" : "D", "octave" : "2"},
    {"instrument" : "piano", "key" : "D#2", "color" : "black", "name" : "D", "octave" : "2"},
    {"instrument" : "piano", "key" : "E2", "color" : "white", "name" : "E", "octave" : "2"},
    {"instrument" : "piano", "key" : "F2", "color" : "white", "name" : "F", "octave" : "2"},
    {"instrument" : "piano", "key" : "F#2", "color" : "black", "name" : "F", "octave" : "2"},
    {"instrument" : "piano", "key" : "G2", "color" : "white", "name" : "G", "octave" : "2"},
    {"instrument" : "piano", "key" : "G#2", "color" : "black", "name" : "G", "octave" : "2"},
    {"instrument" : "piano", "key" : "A2", "color" : "white", "name" : "A", "octave" : "2"},
    {"instrument" : "piano", "key" : "A#2", "color" : "black", "name" : "A", "octave" : "2"},
    {"instrument" : "piano", "key" : "B2", "color" : "white", "name" : "B", "octave" : "2"},
    {"instrument" : "piano", "key" : "C3", "color" : "white", "name" : "C", "octave" : "3"},
    {"instrument" : "piano", "key" : "C#3", "color" : "black", "name" : "C", "octave" : "3"},
    {"instrument" : "piano", "key" : "D3", "color" : "white", "name" : "D", "octave" : "3"},
    {"instrument" : "piano", "key" : "D#3", "color" : "black", "name" : "D", "octave" : "3"},
    {"instrument" : "piano", "key" : "E3", "color" : "white", "name" : "E", "octave" : "3"},
    {"instrument" : "piano", "key" : "F3", "color" : "white", "name" : "F", "octave" : "3"},
    {"instrument" : "piano", "key" : "F#3", "color" : "black", "name" : "F", "octave" : "3"},
    {"instrument" : "piano", "key" : "G3", "color" : "white", "name" : "G", "octave" : "3"},
    {"instrument" : "piano", "key" : "G#3", "color" : "black", "name" : "G", "octave" : "3"},
    {"instrument" : "piano", "key" : "A3", "color" : "white", "name" : "A", "octave" : "3"},
    {"instrument" : "piano", "key" : "A#3", "color" : "black", "name" : "A", "octave" : "3"},
    {"instrument" : "piano", "key" : "B3", "color" : "white", "name" : "B", "octave" : "3"},
    {"instrument" : "piano", "key" : "C4", "color" : "white", "name" : "C", "octave" : "4"},
    {"instrument" : "piano", "key" : "C#4", "color" : "black", "name" : "C", "octave" : "4"},
    {"instrument" : "piano", "key" : "D4", "color" : "white", "name" : "D", "octave" : "4"},
    {"instrument" : "piano", "key" : "D#4", "color" : "black", "name" : "D", "octave" : "4"},
    {"instrument" : "piano", "key" : "E4", "color" : "white", "name" : "E", "octave" : "4"},
    {"instrument" : "piano", "key" : "F4", "color" : "white", "name" : "F", "octave" : "4"},
    {"instrument" : "piano", "key" : "F#4", "color" : "black", "name" : "F", "octave" : "4"},
    {"instrument" : "piano", "key" : "G4", "color" : "white", "name" : "G", "octave" : "4"},
    {"instrument" : "piano", "key" : "G#4", "color" : "black", "name" : "G", "octave" : "4"},
    {"instrument" : "piano", "key" : "A4", "color" : "white", "name" : "A", "octave" : "4"},
    {"instrument" : "piano", "key" : "A#4", "color" : "black", "name" : "A", "octave" : "4"},
    {"instrument" : "piano", "key" : "B4", "color" : "white", "name" : "B", "octave" : "4"},
    {"instrument" : "piano", "key" : "C5", "color" : "white", "name" : "C", "octave" : "5"},
    {"instrument" : "piano", "key" : "C#5", "color" : "black", "name" : "C", "octave" : "5"},
    {"instrument" : "piano", "key" : "D5", "color" : "white", "name" : "D", "octave" : "5"},
    {"instrument" : "piano", "key" : "D#5", "color" : "black", "name" : "D", "octave" : "5"},
    {"instrument" : "piano", "key" : "E5", "color" : "white", "name" : "E", "octave" : "5"},
    {"instrument" : "piano", "key" : "F5", "color" : "white", "name" : "F", "octave" : "5"},
    {"instrument" : "piano", "key" : "F#5", "color" : "black", "name" : "F", "octave" : "5"},
    {"instrument" : "piano", "key" : "G5", "color" : "white", "name" : "G", "octave" : "5"},
    {"instrument" : "piano", "key" : "G#5", "color" : "black", "name" : "G", "octave" : "5"},
    {"instrument" : "piano", "key" : "A5", "color" : "white", "name" : "A", "octave" : "5"},
    {"instrument" : "piano", "key" : "A#5", "color" : "black", "name" : "A", "octave" : "5"},
    {"instrument" : "piano", "key" : "B5", "color" : "white", "name" : "B", "octave" : "5"},
    {"instrument" : "piano", "key" : "C6", "color" : "white", "name" : "C", "octave" : "6"},
    {"instrument" : "piano", "key" : "C#6", "color" : "black", "name" : "C", "octave" : "6"},
    {"instrument" : "piano", "key" : "D6", "color" : "white", "name" : "D", "octave" : "6"},
    {"instrument" : "piano", "key" : "D#6", "color" : "black", "name" : "D", "octave" : "6"},
    {"instrument" : "piano", "key" : "E6", "color" : "white", "name" : "E", "octave" : "6"},
    {"instrument" : "piano", "key" : "F6", "color" : "white", "name" : "F", "octave" : "6"},
    {"instrument" : "piano", "key" : "F#6", "color" : "black", "name" : "F", "octave" : "6"},
    {"instrument" : "piano", "key" : "G6", "color" : "white", "name" : "G", "octave" : "6"},
    {"instrument" : "piano", "key" : "G#6", "color" : "black", "name" : "G", "octave" : "6"},
    {"instrument" : "piano", "key" : "A6", "color" : "white", "name" : "A", "octave" : "6"},
    {"instrument" : "piano", "key" : "A#6", "color" : "black", "name" : "A", "octave" : "6"},
    {"instrument" : "piano", "key" : "B6", "color" : "white", "name" : "B", "octave" : "6"},
    {"instrument" : "piano", "key" : "C7", "color" : "white", "name" : "C", "octave" : "7"} /*, 73 Keys
    {"instrument" : "piano", "key" : "C#7", "color" : "black"},
    {"instrument" : "piano", "key" : "D7", "color" : "white"},
    {"instrument" : "piano", "key" : "D#7", "color" : "black"},
    {"instrument" : "piano", "key" : "E7", "color" : "white"},
    {"instrument" : "piano", "key" : "F7", "color" : "white"},
    {"instrument" : "piano", "key" : "F#7", "color" : "black"},
    {"instrument" : "piano", "key" : "G7", "color" : "white"},
    {"instrument" : "piano", "key" : "G#7", "color" : "black"},
    {"instrument" : "piano", "key" : "A7", "color" : "white"},
    {"instrument" : "piano", "key" : "A#7", "color" : "black"},
    {"instrument" : "piano", "key" : "B7", "color" : "white"}   */
]
